---
title: "Overwatch data"
output: ow_html_notebook
---

```{r}
library(brms)
library(tidyverse)
```

```{r}
raw <- read_csv('raw.csv')
```

Remove backfill games.

```{r}
raw <- filter(raw, pick_algo != 'backfill')
```

Replace blank categorical variables with default values.

```{r}
raw <- replace_na(raw, list(comp = 'qp', gender = 'm'))
```

Replace the rest with 0s.

```{r}
names2zero <- setNames(lapply(vector("list", ncol(raw)), function(x) x <- 0), names(raw))
no_na <- replace_na(raw, names2zero)
```

Make composite columns for comments directed at myself or other players.

```{r}
composite <- no_na
any_switch <- pull(composite, 'switch') + pull(composite,'undir_switch')
composite <- add_column(composite, any_switch)

any_sex <- pull(composite, 'sex') + pull(composite,'undir_sex')
composite <- add_column(composite, any_sex)

any_complement <- pull(composite, 'complement') + pull(composite,'undir_complement')
composite <- add_column(composite, any_complement)

any_how2play <- pull(composite, 'how2play') + pull(composite,'undir_how2play')
composite <- add_column(composite, any_how2play)
```

Flatten data from 0, 1, 2, 3... to {0, 1}

```{r}
not_zero <- function(x) {x != 0}
flattened <- mutate_if(composite, is.numeric, function(x) ifelse(x != 0, 1, 0))
```

Find proportion of rows with non-zero.

```{r}
tmp <- flattened %>%
  filter(comp == 'comp', gender == 'f') %>%
  count(switch) %>%
  mutate(freq = n / sum(n))

tmp['freq']
```


```{r}
flattened %>%
  group_by(gender, comp, switch) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n)) %>%
  filter(switch != 0)
```

```{r}
flattened %>%
  group_by(gender, comp, any_switch) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n)) %>%
  filter(any_switch != 0)
```

```{r}
flattened %>%
  group_by(gender, comp, how2play) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n)) %>%
  filter(how2play != 0)
```
```{r}
flattened %>%
  group_by(gender, comp, any_how2play) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n)) %>%
  filter(any_how2play != 0)
```

```{r}
flattened %>%
  group_by(gender, comp, complement) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n)) %>%
  filter(complement != 0)
```

```{r}
flattened %>%
  group_by(gender, comp, any_complement) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n)) %>%
  filter(any_complement != 0)
```

