---
title: "R Notebook"
output: html_notebook
---

```{r}
library(data.table)
library(ggplot2)
```

```{r}
hours <- fread('bls-hours.csv')
summary(hours)
```

```{r}
p <- ggplot(hours, aes(Year, Hours, colour=factor(.), shape=factor(.))) +
  geom_point() +
  theme_minimal() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_color_brewer(palette = "Set1") +
  labs(title = "Hours per day spent reading for personal interest (average)",
       subtitle = "BLS American Time Use Survey",
       colour = "",
       shape = ""
       ) + 
  ylim(c(0, NA))
p
```


```{r}
hours <- fread('bls-pct.csv')
summary(hours)
```


```{r}
p <- ggplot(hours, aes(Year, Participation, colour=factor(.), shape=factor(.))) +
  geom_point() +
  theme_minimal() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_color_brewer(palette = "Set1") +
  labs(title = "Fraction reading for personal interest per day",
       subtitle = "BLS American Time Use Survey",
       colour = "",
       shape = ""
       ) + 
  ylab("Percent") +
  ylim(c(0, NA))
p
```