---
title: "R Notebook"
output: html_notebook
---

Load UCBadmit data.

```{r}
# detach(package:brms)
library(rethinking)
data(UCBadmit)
d <- UCBadmit
```

Use brms.

```{r}
library(tidyverse)
detach(package:rethinking)
library(brms)
rm(UCBadmit)

d
```

Convert gender to 0/1

```{r}
d <- d %>% mutate(male = ifelse(applicant.gender == "male", 1, 0))
```

```{r}
baseline <- brm(data = d, family = binomial,
  admit | trials(applications) ~ 1,
  prior = c(set_prior("normal(0,10)", class = "Intercept")),
  iter = 2500, warmup = 500, cores = 4, chains = 2)
```
```{r}
global_gender <-
  brm(data = d, family = binomial,
      admit | trials(applications) ~ 1 + male,
      prior = c(set_prior("normal(0,10)", class = "Intercept"),
              set_prior("normal(0,10)", class = "b")),
      iter = 2500, warmup = 500, cores = 4, chains = 2)

```
```{r}
waic(baseline, global_gender)
```

```{r}
l_base <- loo(baseline)
l_gg <- loo(global_gender)
```

```{r}
library(loo)
```

Look into pareto_k warnings from loo.

```{r}
pareto_k_table(l_gg)
```


```{r}
plot(l_gg)
```

```{r}
department <-
  brm(data = d, family = binomial,
      admit | trials(applications) ~ 1 + male,
      prior = c(set_prior("normal(0,10)", class = "b")),
      iter = 2500, warmup = 500, cores = 4, chains = 2)
```

```{r}
department_gender <-
  brm(data = d, family = binomial,
      admit | trials(applications) ~ 1 + male + dept,
      prior = c(set_prior("normal(0,10)", class = "b")),
      iter = 2500, warmup = 500, cores = 4, chains = 2)
```
```{r}
loos <- loo(baseline, global_gender, department, department_gender, reloo = T, cores = 4)
```

```{r}
loos
```

Parameter summaries for model.

```{r}
fixef(department_gender) %>% round(digits = 2)
```
```{r}
d <-
  d %>%
  mutate(case = factor(1:12))

d_text <-
  d %>%
  group_by(dept) %>%
  summarise(case = mean(as.numeric(case)),
            admit = mean(admit/applications) + .05)
```


```{r}
predict(department_gender) %>% 
  as_tibble() %>% 
  bind_cols(d) %>% 

ggplot(aes(x = case, y = admit/applications)) +
  geom_pointrange(aes(y = Estimate/applications,
                      ymin = `Q2.5`/applications ,
                      ymax = `Q97.5`/applications),
                  shape = 1, alpha = 1/3) +
  geom_point() +
  geom_line(aes(group = dept)) + 
  geom_text(data = d_text,
            aes(y = admit, label = dept)) + 
  coord_cartesian(ylim = 0:1) +
  labs(y = "Proportion admitted",
       title = "Posterior validation check") +
  theme(axis.ticks.x = element_blank())
```