---
title: "R Notebook"
output: html_notebook
---


```{r}
library(brms)
library(modelr)
library(tidybayes)
library(tidyverse)
```

```{r}
d <- tribble(
  ~author, ~total, ~unqual, ~cond,
  "Dan", 480, 0, 0,
  "Julia", 477, 3, 9,
)
```

```{r}
uq_model <- 
  brm(data = d, family = binomial,
      unqual | trials(total) ~ author,
      prior = c(set_prior("normal(0,10)", class = "b")),
      iter = 5000, warmup = 100, cores = 1, chains = 1)
```


```{r}
newdata <- data.frame(author=c("Dan", "Julia"), total = c(100000,100000))
predict(uq_model, newdata = newdata, probs = c(0.25, 0.75), summary = TRUE) %>%
  as_tibble()
```

```{r}
uq_model
```


```{r}
cd_model <- 
  brm(data = d, family = binomial,
      cond | trials(total) ~ author,
      prior = c(set_prior("normal(0,10)", class = "b")),
      iter = 5000, warmup = 100, cores = 1, chains = 1)
```



```{r}
newdata <- data.frame(author=c("Dan", "Julia"), total = c(100000,100000))
predict(cd_model, newdata = newdata, probs = c(0.25, 0.75), summary = TRUE) %>%
  as_tibble()
```
```{r}
d <- tribble(
  ~author, ~total, ~unqual, ~cond,
  "Dan", 15, 0, 0,
  "Julia", 14, 2, 6,  
)
```


```{r}
uq_model <- 
  brm(data = d, family = binomial,
      unqual | trials(total) ~ author,
      prior = c(set_prior("normal(0,10)", class = "b")),
      iter = 5000, warmup = 100, cores = 1, chains = 1)
```, "Julia"), total = c(100000,100000))
predict(uq_model, newdata = newdata, probs =

```{r}
newdata <- data.frame(author=c("Dan" c(0.25, 0.75), summary = TRUE) %>%
  as_tibble()
```